# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "Iphis Discounts"
client_id = "9259415d609d01b63055b7948726c472"
application_url = "https://718d-2604-3d09-7376-4300-f13e-878-cb8d-e347.ngrok-free.app"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
use_legacy_install_flow = true

[auth]
redirect_urls = [
  "https://718d-2604-3d09-7376-4300-f13e-878-cb8d-e347.ngrok-free.app/api/auth/tokens",
  "https://718d-2604-3d09-7376-4300-f13e-878-cb8d-e347.ngrok-free.app/api/auth/callback"
]

[webhooks]
api_version = "2023-07"

[pos]
embedded = false
