# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "IPHIS BUY X GET Y DISCOUNT"
client_id = "edb82d28444cf7d21aaa27eb6b263f38"
application_url = "https://ddef-14-97-239-178.ngrok-free.app"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
use_legacy_install_flow = true

[auth]
redirect_urls = [
  "https://ddef-14-97-239-178.ngrok-free.app/api/auth/tokens",
  "https://ddef-14-97-239-178.ngrok-free.app/api/auth/callback"
]

[webhooks]
api_version = "2023-10"

  [webhooks.privacy_compliance]
  customer_deletion_url = "https://ddef-14-97-239-178.ngrok-free.app/api/gdpr/customers_redact"
  customer_data_request_url = "https://ddef-14-97-239-178.ngrok-free.app/api/gdpr/customers_data_request"
  shop_deletion_url = "https://ddef-14-97-239-178.ngrok-free.app/api/gdpr/shop_redact"

[app_proxy]
url = "https://ddef-14-97-239-178.ngrok-free.app/api/proxy_route"
subpath = "next-proxy"
prefix = "apps"

[pos]
embedded = false
