# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "IPHIS BUY X GET Y DISCOUNT"
client_id = "4b42b2f5bb7382ab2410f7f5740b6e58"
application_url = "https://8594-14-97-239-178.ngrok-free.app"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [ "https://8594-14-97-239-178.ngrok-free.app/api/auth" ]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false
