name = "Iphis Product Discount"
type = "product_discounts"
api_version = "2023-07"

[build]
command = ""
path = "dist/function.wasm"

[ui.paths]
create = "/iphis_discount_product"
details = "/iphis_discount_product"
