name = "Iphis Order Discount Function"
type = "order_discounts"
api_version = "2023-07"

[build]
command = ""
path = "dist/function.wasm"

[ui.paths]
create = "/iphis_discount"
details = "/iphis_discount"
